export const CONTACT_ERROR = 'CONTACT_ERROR';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL';
export const GET_CONTACTS_FAIL = 'GET_CONTACTS_FAIL';
export const CONTACT_LOADING = 'CONTACT_LOADING';
export const GET_CONTACT_SUCCESS = 'GET_CONTACT_SUCCESS';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';